- name: setting up the catalogue component 
  hosts: catalogue
  tasks:
  - name: running the shell script to run some configurations
    shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: setting up the nodejs 
    become: yes 
    yum: 
      name: nodejs
      state: present
  - name: checking the roboshop user 
    command: id roboshop 
    register: output 
    ignore_errors: True 
  - name: creating the user if not exist 
    user: 
      name: roboshop 
      uid: 1001
      gid: 1001 
    when: output.rc== 1
    