- name: setting up the catalogue component 
  hosts: catalogue
  tasks:
  - name: running the shell script to run some configurations
    shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: setting up the nodejs 
    become: yes 
    yum: 
      name: nodejs
      state: present
  - name: checking the roboshop user 
    command: id roboshop 
    register: output 
    ignore_errors: True 
  - name: creating the user if not exist 
    become: yes
    user: 
      name: roboshop 
    when: output.rc== 1
  - name: creating the app directory 
    file: 
      path: /home/centos/ 
      state: directory 
  - name: download the application code to created app directory 
    command: curl https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    args: 
      chdir: cd /app


    