- name: installing the playbooks 
  hosts: localhost 
  become: yes 
  variables: 
    packages: 
      nginx: installed 
  tasks: 
  - name: installing the packages 
    yum: 
      name: "{{item.key}}"
      state: "{{item.value}}"
    with_dict: 
      -"{packages}"

