- name: installing the playbooks 
  hosts: localhost 
  become: yes 
  tasks:
  - name: check the file is exist or not 
    stat: 
      path: mohan.txt
    register: output
  - name: printing the output 
    debug: 
      msg: "{{output.stat.inode}}"
      

