- name: configuring the nginx service 
  hosts: chiru 
  tasks: 
  - name: copying the repo to the server 
    become: yes
    copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo 
  - name: installing the mongodb 
    become: yes
    yum: 
      name: mongodb-org
      state: present 
  - name: changing the server configuration 
    become: yes 
    replace:
      path: /ect/mongod.conf 
      regrex: "127.0.0.1"
      replace: "0.0.0.0"
  
  