- name: configuring the nginx service 
  hosts: chiru 
  tasks: 
  - name: copying the repo to the server 
    become: yes
    copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo 
  - name: installing the mongodb 
    become: yes
    yum: 
      name: mongod 
      state: present 
  
  