- name: installing the playbooks 
  hosts: web
  become: yes 
  tasks: 
  - name: installing the nginx 
    yum : 
      name: nginx 
      state: present 
  - name: starting the nginx service 
    service: 
      name: nginx 
      state: started 
      enabled: True 
  - name: removing the deafult web page in the nginx server 
    file: 
      path: /usr/share/nginx/html/
      state: absent
  - name: downloading the content from the aws s3
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /home/centos/A1/
      mode: "0777"
  - name: unzip the file 
    unarchive: 
      src: /home/centos/A1/web.zip
      dest: /usr/share/nginx/html



  




    


