- name: installing the playbooks 
  hosts: mongodb
  become: yes 
  tasks: 
  - name: installing the nginx 
    yum : 
      name: nginx 
      state: present 
  - name: starting the nginx service 
    service: 
      name: nginx 
      state: started 
      enabled: True 
  - name: removing the deafult web page in the nginx server 
    command: rm -f *
    args: 
      chdir: /usr/share/nginx/html
  - name: downloading the content from the aws s3
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /home/centos/
      mode: "0777"
  - name: unzip the file 
    unarchive: 
      src: /home/centos/web.zip
      dest: /usr/share/nginx/html
    register: output
    ignore_errors: True
  - name: creating the directory if not exisits
    command: mkdir html 
    args: 
      chdir: /usr/share/nginx/
    when: output.changed =="false"
  - name: copy the config file to the server 
    copy: 
      src: roboshop.conf 
      dest: /etc/nginx/default.d/roboshop.conf 
  - name: restart the nginx servicne 
    service: 
      name: nginx 
      state: restarted



  




    


