- name: mprintitn the variable 
  debug: 
    msg: "this is the mohan who are you"
- name: this is from  role from common 
  import_role: 
    name: common 
    tasks_from: chiru.yaml
- name: this is from the roles common compoent and mohan file
  import_role: 
    name: common 
    tasks_from: mohan.yaml
  notify: 
  - fuck you
