- name: mprintitn the variable 
  debug: 
    msg: "this is the mohan who are you"
- name: this is from  role from common 
  import_role: 
    name: common 
    tasks_from: chiru.yaml
- name: this for instaling the nginx 
  yum: 
    name: nginx 
    state: present 
  notify: 
    - mohan

